modLoader="javafml"
loaderVersion="[32,)"
license="All rights reserved"
issueTrackerURL="https://github.com/teamauroramods/EnhancedMushrooms/issues"

[[mods]]
    modId="enhanced_mushrooms"
    version="${file.jarVersion}"
    displayName="Enhanced Mushrooms"
    displayURL="https://discord.gg/BgE4EpP"
    logoFile="logo.png"
    authors="Team Aurora"
    description="New mushroom-based wood types and a couple mushroom foods."

[[dependencies.enhanced_mushrooms]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhanced_mushrooms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.enhanced_mushrooms]]
    modId="abnormals_core"
    mandatory=true
    versionRange="[3.0.2,)"
    ordering="AFTER"
    side="BOTH"